apiVersion: v1
kind: Service
metadata:
  name: ai-music-composer-service
spec:
  type: LoadBalancer
  selector:
    app: ai-music-composer
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
